spring.application.name=service_register
server.port=8761
eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

#promethues configurations
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=service_register

#management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
#management.endpoints.web.base-path=/actuator