spring.application.name=users-service
server.port=8080
spring.session.jdbc.initialize-schema=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/users?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=my1234
spring.jpa.hibernate.ddl-auto=update
jwt.secret=nchdenedjeyeneg364858939$%^&#7374HWNKFSDHEGYJKSDFJIOHDAG#NJDHIEDD
jwt.expiration=86400000
spring.security.oauth2.client.registration.google.client-id=731263991590-h3e6ml9fel1i7780e6bajcnbrtng8q81.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
#Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Fail fast on serialization errors
spring.kafka.producer.properties.spring.json.fail-on-empty-beans=false
spring.kafka.producer.properties.spring.json.write-dates-as-timestamps=false
# Enable type info in Kafka message headers
spring.kafka.producer.properties.spring.json.add.type.headers=true
# SSL Configuration (Required for RDS)
#spring.datasource.hikari.data-source-properties.ssl=true
#spring.datasource.hikari.data-source-properties.sslmode=require
