# ========================
# Server Config
# ========================
server.port=8090

# ========================
# Application Config
# ========================
spring.application.name=api-gateway

# ========================
# Spring Cloud Gateway Config
# ========================

# Default Filters
#spring.cloud.gateway.server.webflux.default-filters=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
# Global CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
# ------------------------
# User Authentication Routes (NO JWT)
# ------------------------

# User Register
spring.cloud.gateway.server.webflux.routes[0].id=USERS-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2
#spring.cloud.gateway.routes[0].predicates[1]=Method=POST
#spring.cloud.gateway.routes[0].filters[0].name=AddRequestHeader
#spring.cloud.gateway.routes[0].filters[0].args.name=X-Gateway-Request
#spring.cloud.gateway.routes[0].filters[0].args.value=true

# User Login
#spring.cloud.gateway.routes[1].id=USERS-SERVICE
#spring.cloud.gateway.routes[1].uri=lb://USERS-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**
#spring.cloud.gateway.routes[1].predicates[1]=Method=POST
##spring.cloud.gateway.routes[1].filters[0].name=AddRequestHeader
##spring.cloud.gateway.routes[1].filters[0].args.name=X-Gateway-Request
##spring.cloud.gateway.routes[1].filters[0].args.value=true

# ------------------------
# User Service (With JWT Filter)
# ------------------------
spring.cloud.gateway.server.webflux.routes[1].id=USERS-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/user/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=JwtAuthenticationFilter

# ------------------------
# Product Service (With JWT Filter)
# ------------------------
spring.cloud.gateway.server.webflux.routes[2].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/products/**
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=JwtAuthenticationFilter

logging.level.root=info
logging.level.org.springframework.cloud.gateway.server.webmvc=INFO
logging.level.org.springframework.cloud.gateway=trace
#logging.level.org.springframework.cloud.gateway=DEBUG

# ------------------------
# Cart Service (With JWT Filter)
# ------------------------
spring.cloud.gateway.server.webflux.routes[3].id=CART
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/cart/**
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=JwtAuthenticationFilter

# ------------------------
# Order Service (With JWT Filter)
# ------------------------
spring.cloud.gateway.server.webflux.routes[4].id=ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/order/**
spring.cloud.gateway.server.webflux.routes[4].filters[0].name=JwtAuthenticationFilter

# OAuth
spring.cloud.gateway.server.webflux.routes[5].id=USERS-SERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/oauth/**
# ========================
# Eureka Client Config
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# ========================
# JWT Config
# ========================
jwt.secret=nchdenedjeyeneg364858939$%^&#7374HWNKFSDHEGYJKSDFJIOHDAG#NJDHIEDD
jwt.expiration=86400000

# ========================
# Actuator / Management Endpoints
# ========================
#management.endpoints.web.exposure.include=health,info,routes,gateway

#promethues configurations
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=api-gateway

#management.endpoint.prometheus.enabled=true
#management.prometheus.metrics.export.enabled=true
#management.endpoints.web.base-path=/actuator