spring.application.name=notification
server.port=8085
spring.session.jdbc.initialize-schema=always
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udarachamod03@gmail.com
spring.mail.password=yqaa lcoo pgya taed
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Application settings
app.email.from=udarachamod03@gmail.com
app.email.support=udarachamod03@gmail.com

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mail-group-id-v1
spring.kafka.consumer.auto-offset-reset=earliest
#Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Important: Tell Spring Kafka how to read the JSON object
# spring.kafka.consumer.properties.spring.json.value.default.type=com.example.notification.Model.Order

# Enable debug for Spring's configuration logic
logging.level.org.springframework.context=DEBUG
logging.level.org.springframework.kafka=DEBUG

# Enable debug for the consumer execution
logging.level.com.uchamod.estore=DEBUG

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=true
# Type mapping for multiple event types
spring.kafka.consumer.properties.spring.json.type.mapping=com.example.order.Model.Order:com.uchamod.notification.Model.Order,com.uchamod.user.Model.User:com.uchamod.notification.Model.User
