spring.application.name=order-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/order?createDatabaseIfNotExist=true

spring.datasource.username=postgres
spring.datasource.password=my1234
spring.jpa.hibernate.ddl-auto=update
server.port=8084
spring.session.jdbc.initialize-schema=always
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udarachamod03@gmail.com
spring.mail.password=yqaa lcoo pgya taed
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Application settings
app.email.from=udarachamod03@gmail.com
app.email.support=udarachamod03@gmail.com

# SSL Configuration (Required for RDS)
#spring.datasource.hikari.data-source-properties.ssl=true
#spring.datasource.hikari.data-source-properties.sslmode=require

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
#Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Fail fast on serialization errors
spring.kafka.producer.properties.spring.json.fail-on-empty-beans=false
spring.kafka.producer.properties.spring.json.write-dates-as-timestamps=false

# Enable type info in Kafka message headers
spring.kafka.producer.properties.spring.json.add.type.headers=true
