spring.application.name=Cart
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cart

spring.datasource.username=postgres
spring.datasource.password=my1234
spring.jpa.hibernate.ddl-auto=update
server.port=8082

# SSL Configuration (Required for RDS)
# spring.datasource.hikari.data-source-properties.ssl=true
# spring.datasource.hikari.data-source-properties.sslmode=require

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-group-id-v2
spring.kafka.consumer.auto-offset-reset=earliest
#Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Fail fast on serialization errors
spring.kafka.producer.properties.spring.json.fail-on-empty-beans=false
spring.kafka.producer.properties.spring.json.write-dates-as-timestamps=false

# Enable debug for Spring's configuration logic
logging.level.org.springframework.context=DEBUG
logging.level.org.springframework.kafka=DEBUG

# Enable debug for the consumer execution
logging.level.com.uchamod.estore=DEBUG

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=true

# Type mapping for multiple event types
spring.kafka.consumer.properties.spring.json.type.mapping=UserDeleteEvent:com.uchamod.commonmodules.Models.UserDeleteEvent
#promethues configurations
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=Cart

management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoints.web.base-path=/actuator